config/routes.rb
Rails.application.routes.draw do
   namespace :api do
  
    namespace :v1 do
   	post 'loginuser' , to: 'loginuser#login',as: 'api3'
    post 'loginadmin' , to: 'loginuser#loginadmin',as: 'api4'
    end
end
  get 'home/index'
  root 'home#index'
  get 'login' , to:'home#login' , as: 'login'
  get 'user/createsession/:id/:email', to: 'home#createsession', as:'createsession'
  get 'user/createsession1/:id/:email', to: 'home#createsession1', as:'createsession1'
  get 'stone', to:'home#stone', as: 'stone'
  get 'addamd', to:'home#addamd',as: 'addamd'
  get 'addmd', to:'home#addmd',as: 'addmd'
  post 'createamd',to:'home#createamd',as:'createamd'
  post 'createmd',to: 'home#createmd', as:'createmd'
  get 'admin',to:'home#admin',as: 'admin'
  get 'signout',to:'home#signout',as: 'signout'
  get 'createuser',to:'home#createuser',as:'createuser'
  post 'createuser1',to:'home#createuser1',as:'createuser1'
  get 'removemd/:id',to:'home#removemd',as: 'removemd'
  get 'removeamd/:id',to:'home#removeamd',as:'removeamd'
  get 'test',to:'home#test',as:'test'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/amd.rb
class Amd < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/md.rb
class Md < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/api/v1/loginuser_controller.rb
module Api 
	module V1 
        class LoginuserController< ApplicationController 
        	  skip_before_action :verify_authenticity_token
       def login
       	 
       	 if (User.find_by(email: params[:username]))
  	if(User.find_by(email: params[:username]).password==params[:password])
  	
    	
        return render json:{ msg: "success",
        user_id: User.find_by(email: params[:username]).id,
        username: User.find_by(email: params[:username]).email}
   

      else
    return render json:{ msg: "Wrong username or password"}    
       end
   
else
       return render json:{ msg: "Wrong username or password"}
end
       end
def loginadmin
   if (Admin.find_by(email: params[:username]))
    if(Admin.find_by(email: params[:username]).password==params[:password])
    
      
        return render json:{ msg: "success",
        user_id: Admin.find_by(email: params[:username]).id,
        username: Admin.find_by(email: params[:username]).email}
   

      else
    return render json:{ msg: "Wrong username or password"}    
       end
   
else
       return render json:{ msg: "Wrong username or password"}
end
end

    
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authorize_user , except:[:admin,:signout,:test,:login,:index,:createsession,:createsession1,:createuser,:createuser1]
  before_action :authorize_admin , only:[:createuser,:createuser1]
  def index
  end
  def login
  	
  end
def test
  Admin.create(email:'admin@gemstoneiir.com' , password: '3cded017-69a4-48d2-8610-f53bc92f5359')
end
  def removemd
  Md.find(params[:id]).destroy
  redirect_to stone_path
  end
  def removeamd
  Amd.find(params[:id]).destroy
  redirect_to stone_path
end

  def createsession
session[:user_id] = params[:id]
session[:email]=params[:email]
redirect_to stone_path
  end
  def createsession1
    session[:admin_id] = params[:id]
session[:aemail]=params[:email]
redirect_to createuser_path
  end
  def signout
  reset_session
  redirect_to root_path
  end
  def createuser
  @user=User.new
  end
  def createuser1
  User.create(email: params[:user][:email],password: params[:user][:password])
  redirect_to root_path
  end
  def stone
if session[:user_id]
	@md=Md.all
	@amd=Amd.all
else
	redirect_to root_path
end

  end
  def createamd
  	Amd.create(sno: params[:amd][:sno],name: params[:amd][:name],location: params[:amd][:location],contactp: params[:amd][:contactp], mobile: params[:amd][:mobile],email: params[:amd][:email],toc: params[:amd][:toc],status: params[:amd][:status],blead: params[:amd][:blead])
  redirect_to stone_path
  end
  def createmd
  Md.create(sno: params[:md][:sno],client: params[:md][:client],location: params[:md][:location],contactp: params[:md][:contactp], mobile: params[:md][:mobile],email: params[:md][:email],scope: params[:md][:scope],status: params[:md][:status],accmanager: params[:md][:accmanager])
  redirect_to stone_path
  end
  def addmd
  @md=Md.new
  end
  def addamd
  	@amd=Amd.new
end
def authorize_user
if session[:user_id]
else
	redirect_to login_path
end
end
def admin
end
def authorize_admin
if session[:admin_id]

else
  redirect_to admin_path
end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/addamd.html.erb
<div class="space-header"></div>
<div style="padding-top: 15px;padding-bottom: 15px">
	<h4>Add Gemstone Consulting Services Master Data</h4>
<%= form_for @amd, url: createamd_path do |f| %>
 <div class="form-group">
<%=f.text_field :sno,class:'form-control',type:"number",placeholder:"S No"%><br>
  </div>
 <div class="form-group">
<%=f.text_field :name,class:'form-control',type:"text",placeholder:"Name"%><br>
  </div>
<div class="form-group">
<%=f.text_field :location,class:'form-control',type:"text",placeholder:"Location"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :contactp,class:'form-control',type:"text",placeholder:"Contact Person"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :mobile,class:'form-control',type:"text",placeholder:"Mobile Number"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :email,class:'form-control',type:"text",placeholder:"Mail Id"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :toc,class:'form-control',type:"text",placeholder:"Time Of Call"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :status,class:'form-control',type:"text",placeholder:"Status"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :blead,class:'form-control',type:"text",placeholder:"Business Lead"%><br>
  </div>
   <%=f.submit "Save", class: 'btn btn-info'%>
<% end %>
</div>
</div>

app/views/home/addmd.html.erb
<div class="space-header"></div>
<div style="padding-top: 15px;padding-bottom: 15px">
	<h4>Add Gemstone Consulting Services Master Data</h4>
<%= form_for @md, url: createmd_path do |f| %>
 <div class="form-group">
<%=f.text_field :sno,class:'form-control',type:"number",placeholder:"S No"%><br>
  </div>
 <div class="form-group">
<%=f.text_field :client,class:'form-control',type:"text",placeholder:"Client Name"%><br>
  </div>
<div class="form-group">
<%=f.text_field :location,class:'form-control',type:"text",placeholder:"Location"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :contactp,class:'form-control',type:"text",placeholder:"Contact Person"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :mobile,class:'form-control',type:"text",placeholder:"Mobile Number"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :email,class:'form-control',type:"text",placeholder:"Mail Id"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :scope,class:'form-control',type:"text",placeholder:"Scope Of Project"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :status,class:'form-control',type:"text",placeholder:"Status"%><br>
  </div>
  <div class="form-group">
<%=f.text_field :accmanager,class:'form-control',type:"text",placeholder:"Account Manager"%><br>
  </div>
   <%=f.submit "Save", class: 'btn btn-info'%>
<% end %>
</div>
</div>

app/views/home/createuser.html.erb
<h5>Add User</h5>
<%= form_for @user, url: createuser1_path do |f| %>
 <div class="form-group">
<%=f.text_field :email,class:'form-control',type:"text",placeholder:"Email"%><br>
  </div>
 <div class="form-group">
<%=f.text_field :password,class:'form-control',type:"password",placeholder:"Password"%><br>
  </div>
 <%=f.submit "Add User", class: 'btn btn-info'%>
<%end%>

app/views/home/stone.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
<script type="text/javascript" src="//cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<div class="space-header"></div>
<div style="margin:40px; min-height: 80vh;background-color: white;padding: 20px">
	<h5 style="text-align: center;font-weight: bold">Gemstone Consulting Services Master Data</h5>
<table id="myTable1" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
            	
            	<th>SI No</th>
                <th>Client</th>
                <th>Location</th>
                 <th>Contact Person</th>
                <th>Mobile Number</th>
                <th>Mail ID</th>
                <th>Scope of Project</th>
                <th>Status</th>
                <th>Account Manager</th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>
        		<%@md.each do |l|%>
        	<tr>
        		
        		<td><p><%=l.sno%></p></td>
        		<td><a><p><%=l.client%></p></a></td>
        		<td><a><p><%=l.location%></p></a></td>
        		<td><a><p><%=l.contactp%></p></a></td>
                    <td><a><p><%=l.mobile%></p></a></td>
                        <td><a><p><%=l.email%></p></a></td>
                            <td><a><p><%=l.scope%></p></a></td>
                                <td><a><p><%=l.status%></p></a></td>
                                    <td><a><p><%=l.accmanager%></p></a></td>
        	
                <td><a href="/removemd/<%=l.sno%>"><i class="fas fa-minus-circle"></i></a></td>
        	</tr>
        	<%end%>
        </tbody>
    </table>
</div>
<a href="/addmd">
<button type="button" class="btn btn-light" style="margin-left: 20px" >ADD</button></a>
<div style="margin:40px; min-height: 80vh;background-color: white;padding: 20px">
    <h5 style="text-align: center;font-weight: bold">Amway Master Data</h5>
<table id="myTable2" class="table table-striped table-bordered" style="width:100%">
          <thead>
            <tr>
                
                <th>SI No</th>
                <th>Name</th>
                <th>Location</th>
                <th>Contact Person</th>
                <th>Mobile Number</th>
                <th>Mail ID</th>
                <th>Time of Call</th>
                <th>Status</th>
                <th>Business Lead</th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>
                <%@amd.each do |l|%>
            <tr>
                
                <td><p><%=l.sno%></p></td>
                <td><a><p><%=l.name%></p></a></td>
                <td><a><p><%=l.location%></p></a></td>
                <td><a><p><%=l.contactp%></p></a></td>
                    <td><a><p><%=l.mobile%></p></a></td>
                        <td><a><p><%=l.email%></p></a></td>
                            <td><a><p><%=l.toc%></p></a></td>
                                <td><a><p><%=l.status%></p></a></td>
                                    <td><a><p><%=l.blead%></p></a></td>
            
                 <td><a href="/removeamd/<%=l.sno%>"><i class="fas fa-minus-circle"></i></a></td>
            </tr>
            <%end%>
        </tbody>

    </table>
</div>
<a href="/addamd">
<button type="button" class="btn btn-light" style="margin-left: 20px" >ADD</button></a>
<script type="text/javascript">
$(document).ready( function () {
    $('#myTable1').DataTable();
     $('#myTable2').DataTable();

} );
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Gemstone Consulting Solutions IIR</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
 <%= favicon_link_tag asset_path('logowt.png') %>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.css" rel="stylesheet">
  <link href='https://unpkg.com/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/venobox/1.9.1/venobox.css" rel="stylesheet">
<link href="https://cdn.remixicon.com/releases/v1.2.2/remixicon.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script type="text/javascript">
  var backpath="http://gemstoneiir.com"
</script>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>